APT::FTPArchive::Release::Origin "NeeXtra Repo";
APT::FTPArchive::Release::Label "NeeXtra Repo";
APT::FTPArchive::Release::Suite "NeextraReleases";
APT::FTPArchive::Release::Version "1.0";
APT::FTPArchive::Release::Codename "neextra";
APT::FTPArchive::Release::Architectures "all";
APT::FTPArchive::Release::Components "neextra";
APT::FTPArchive::Release::Description "The neextrarepo!";
